// maps name to material icon
export const athleticOptions = {
  'Badminton': 'badminton',
  'Basketball': 'basketball',
  'Bowling': 'bowling',
  'Cheerleading': 'bullhorn-variant',
  'Cross Country': 'run',
  'Dance': 'human-female-dance',
  'Fencing': 'fencing',
  'Field Hockey': 'hockey-sticks',
  'Football': 'football',
  'Golf': 'golf',
  'Gymnastics': 'gymnastics',
  'Lacrosse': 'racquetball',
  'Other': 'pencil',
  'Ping Pong': 'table-tennis',
  'Rugby': 'rugby',
  'Skiing': 'ski',
  'Snowboarding': 'snowboard',
  'Soccer': 'soccer',
  'Softball': 'baseball-bat',
  'Swimming': 'swim',
  'Tennis': 'tennis',
  'Track': 'shoe-sneaker',
  'Volleyball': 'volleyball',
  'Water Polo': 'water-polo',
  'Weightlifting': 'weight-lifter',
  'Wrestling': 'kabaddi',
  '': 'close',
}
